name: spv
description: Sporza Voetbal in Flutter
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 0.1.2
  built_value: 6.2.0
  built_collection: 4.1.0
  http: 0.12.0
  rxdart: 0.20.0
  path_provider: 0.4.1

dev_dependencies:
  build_runner: 1.1.2
  built_value_generator: 6.2.0
  test: 1.5.1+1
  mockito: ^3.0.2
  image_test_utils: ^1.0.0
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  fonts:
  - family: Ginger
    fonts:
    - asset: fonts/ginger/ginger_bold.ttf
      weight: 500
    - asset: fonts/ginger/ginger_regular.ttf
      style: normal
  - family: Forma
    fonts:
    - asset: fonts/forma/forma_djr_micro_black.ttf
      weight: 800
      style: normal
    - asset: fonts/forma/forma_djr_micro_blackitalic.ttf
      weight: 800
      style: italic
    - asset: fonts/forma/forma_djr_micro_bold.ttf
      style: normal
      weight: 800
    - asset: fonts/forma/forma_djr_micro_bolditalic.ttf
      weight: 800
      style: italic
    - asset: fonts/forma/forma_djr_micro_extralight.ttf
      style: normal
      weight: 200
    - asset: fonts/forma/forma_djr_micro_extralightitalic.ttf
      weight: 200
      style: italic
    - asset: fonts/forma/forma_djr_micro_italic.ttf
      weight: 400
      style: italic
    - asset: fonts/forma/forma_djr_micro_light.ttf
      style: normal
      weight: 200
    - asset: fonts/forma/forma_djr_micro_lightitalic.ttf
      weight: 200
      style: italic
    - asset: fonts/forma/forma_djr_micro_medium.ttf
      weight: 400
      style: normal
    - asset: fonts/forma/forma_djr_micro_mediumitalic.ttf
      style: italic
      weight: 400
    - asset: fonts/forma/forma_djr_micro_regular.ttf
      weight: 400
      style: normal
