image: nathansamson/flutter-builder-docker

clone:
  depth: 5

pipelines:
  branches:
    master:
      - parallel:
          - step:
              caches:
                - flutterappcache
                - androidgradle
                - gradlewrapper
              name: Build and Test App
              script:
                - cd spv
                - flutter packages get
                - flutter packages pub run build_runner build
                - flutter test
          - step:
              caches:
                - flutterservicecache
                - androidgradle
                - gradlewrapper
              name: Build and Test Service Layer
              script:
                - cd spv/service_layer
                - flutter packages get
                - flutter packages pub run build_runner build
                - flutter test

definitions:
  caches:
    flutterappcache: spv/build
    flutterservicecache: spv/service_layer/build
    androidgradle: spv/android/.gradle
    gradlewrapper: ~/.gradle/wrapper