image: nathansamson/flutter-builder-docker

clone:
  depth: 5

pipelines:
  branches:
    master:
      - parallel:
          - step:
              caches:
                - flutterappcache
                - androidgradle
                - gradlewrapper
              name: Build and Test App
              script:
                - cd spv/
                - sh ./buildTestAll.sh

definitions:
  caches:
    flutterappcache: spv/build
    flutterservicecache: spv/service_layer/build
    androidgradle: spv/android/.gradle
    gradlewrapper: ~/.gradle/wrapper