image: nathansamson/flutter-builder-docker

clone:
  depth: 5

pipelines:
  branches:
    master:
      - step:
          caches:
            - flutterappcache
            - flutterservicecache
            - androidgradle
            - gradlewrapper
          name: Build and test
          script:
            - cd spv
            - flutter packages get
            - flutter packages pub run build_runner build
            - flutter test
            - cd service_layer
            - flutter packages get
            - flutter packages pub run build_runner build
            - flutter test

definitions:
  caches:
    flutterappcache: spv/build
    flutterservicecache: spv/service_layer/build
    androidgradle: spv/android/.gradle
    gradlewrapper: ~/.gradle/wrapper