image: nathansamson/flutter-builder-docker

clone:
  depth: 5

pipelines:
  branches:
    master:
      - step:
          name: Get Packages
          caches:
            - fluttercache
          script:
            - cd spv
            - flutter packages get
      - step:
          name: Build Runner
          caches:
            - androidgradle
            - gradlewrapper
          script:
            - cd spv
            - flutter packages pub run build_runner build
      - step:
          name: Test
          caches:
            - androidgradle
            - gradlewrapper
          script:
            - cd spv
            - flutter test

definitions:
  caches:
    fluttercache: spv/build
    androidgradle: spv/android/.gradle
    gradlewrapper: ~/.gradle/wrapper