name: service_layer_spv
description: Represent the service layer responsible for the Sporza Voetbal calls
version: 0.0.1
author: Tim Rijckaert
homepage: http://www.vrt.be

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 0.1.2
  built_value: 6.2.0
  built_collection: 4.1.0
  http: 0.12.0
  rxdart: 0.20.0
  path_provider: 0.4.1

  common_spv:
    path: ../common

dev_dependencies:
  build_runner: 1.1.2
  built_value_generator: 6.2.0
  test: 1.5.1+1
  mockito: 4.0.0
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
